# 开发环境配置文件
server:
  port: 81
#解决中文乱码问题
  tomcat:
    uri-encoding: UTF-8
#Thymeleaf 相关配置
spring:
  thymeleaf:
    cache: false
  datasource: # 数据库配置
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${datasource.url}?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    hikari:
      maximum-pool-size: 10 # 最大连接池数
      max-lifetime: 1770000
#redis相关配置
  redis:
    database: 5
    # 配置Redis的主机地址
    host: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 5000
    jedis:
      pool:
        # 连接池中的最大空闲连接，默认值也是8。
        max-idle: 500
        # 连接池中的最小空闲连接，默认值也是0。
        min-idle: 50
        # 如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)
        max-active: 1000
        # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException
        max-wait: 2000
#解决中文乱码问题
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true
##ActiveMQ的配置
#  activemq:
#    # activemq url
#    broker-url: tcp://localhost:61616
#    in-memory: true
#    pool:
#      # 如果此处设置为true，需要添加activemq-pool的依赖包，否则会自动配置失败，无法注入JmsMessagingTemplate
#      enabled: false
## 开通发布/订阅消息的消费（默认为false 该配置是 false 的话，则为点对点消息）
#  jms:
#    pub-sub-domain: true
# 整合springDataJpa
  jpa:
    database: mysql
    # JPA的配置了show-sql用来在控制台输出JPA自动生成的sql语句
    show-sql: true
# springDataJpa自动建表
    hibernate:
      ddl-auto: update
# 邮件发送
  mail:
    host: smtp.qq.com
    #邮箱名如：298692628@qq.com
    username: 298692628@qq.com
    #邮箱授权码如：qweqtrtyggdv
    password: bxyitdyasvzasjbgdi
#数据库地址
datasource:
  url: localhost:3306/blog_test
mybatis:
  # 指定别名设置的包为所有entity
  type-aliases-package: com.lyj.entity
  configuration:
    map-underscore-to-camel-case: true # 驼峰命名规范
  mapper-locations: # mapper映射文件位置
    - classpath:mapper/*.xml

classpath: /static

